DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15) NOT NULL,
    DEPT_NAME VARCHAR(30),
    DEPT_LOCATION VARCHAR(50)
);

CREATE TABLE PROJECT(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30),
    BEGIN_DATE DATE,
    END_DATE DATE
);

CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15),
    POSITION CHAR(10),
    NAME VARCHAR2(15),
    HIRE_DATE DATE,
    SALARY NUMBER
);

CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER,
    PJT_NO NUMBER,
    PJT_STATE NUMBER NOT NULL
);

-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
ALTER TABLE PROJECT
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY(PJT_NO);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY(PCD_NO);

-- 외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
        REFERENCES DEPARTMENT(DEPT_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY(PJT_NO)
        REFERENCES PROJECT(PJT_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEE(EMP_NO);



-- 기본키 제거
-- FK에 의해서 참조되고 있는 PK는 제거할 수 없음.
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT; -- DEPARTMENT의 PRIMARY KEY를 참조받고 있는 값이 있어서 오류 발생(EMPLOYEE의 FOREIGN KEY 먼저 제거해야함)

ALTER TABLE DEPARTMENT             
    DROP PRIMARY KEY;              -- 이름이 지정되지 않은 PRIMARY KEY 삭제 방법

 ALTER TABLE PROCEEDING
    DROP CONSTRAINT PK_PROCEEDING;

-- 외래키 제거
-- DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
-- DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있음
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT; -- DEPARTEMENT의 PK 제거를 위해 EMPLOYEE FK 제거 => 58번 행의 코드 실행 가능. 





