DROP TABLE ENROLL;
DROP TABLE LECTURE;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;
DROP TABLE STUDENT;

CREATE TABLE PROFESSOR(
    PROF_NO         NUMBER              NOT NULL, --PK
    PROF_NAME       VARCHAR2(30 BYTE)   NULL,
    PROF_MAJOR      VARCHAR2(30 BYTE)   NULL
);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PROF_NO);

CREATE TABLE COURSE(
    COUR_NO         NUMBER              NOT NULL, --PK
    COUR_NAME       VARCHAR2(30 BYTE)   NULL,
    COUR_GRADE      NUMBER(1)           NULL
);

ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NO);

CREATE TABLE STUDENT(
    STU_NO          NUMBER             NOT NULL, --PK
    STU_NAME        VARCHAR2(30 BYTE)  NULL,
    STU_REG         VARCHAR2(50 BYTE)  NULL,
    STU_GRADE       NUMBER             NULL,
    PROF_NO         NUMBER             NOT NULL
);

ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(PROF_NO)
        REFERENCES PROFESSOR(PROF_NO);

CREATE TABLE ENROLL(
    ENR_NO          NUMBER              NOT NULL, --PK
    STU_NO          NUMBER              NOT NULL, --FK
    COUR_NO         NUMBER              NOT NULL, --FK
    ENR_DATE        DATE                NULL
);

ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO)
        REFERENCES STUDENT(STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COUR_NO)
        REFERENCES COURSE(COUR_NO);
        
CREATE TABLE LECTURE(
    LEC_NO          NUMBER              NOT NULL, --PK
    PROF_NO         NUMBER              NOT NULL, --FK
    ENR_NO          NUMBER              NOT NULL, --FK
    LEC_NAME        VARCHAR2(30 BYTE)   NULL,
    LEC_PLACE       VARCHAR2(30 BYTE)   NULL
);

ALTER TABLE LECTURE
    ADD CONSTRAINT LEC_NO PRIMARY KEY(LEC_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PROF_NO)
        REFERENCES PROFESSOR(PROF_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO)
        REFERENCES ENROLL(ENR_NO);
        
        

INSERT INTO PROFESSOR(PROF_NO, PROF_NAME, PROF_MAJOR) VALUES (1, '제임스', '전산');
INSERT INTO PROFESSOR(PROF_NO, PROF_NAME, PROF_MAJOR) VALUES (2, '앨리스', '회계');
INSERT INTO PROFESSOR(PROF_NO, PROF_NAME, PROF_MAJOR) VALUES (3, '스미스', '영화');

-- 2. COURSE 테이블 데이터 입력
INSERT INTO COURSE(C_NO, C_NAME, C_UNIT) VALUES (11, '자바', 3);
INSERT INTO COURSE(C_NO, C_NAME, C_UNIT) VALUES (22, '데이터베이스', 3);
INSERT INTO COURSE(C_NO, C_NAME, C_UNIT) VALUES (33, '서버프로그램', 3);

-- 3. STUDENT 테이블 데이터 입력
INSERT INTO STUDENT(S_NO, S_NAME, S_ADDRESS, S_GRADE_NO, P_NO) VALUES (10101, '김학생', '서울', 1, 3);
INSERT INTO STUDENT(S_NO, S_NAME, S_ADDRESS, S_GRADE_NO, P_NO) VALUES (10102, '이학생', '경기', 1, 3);
INSERT INTO STUDENT(S_NO, S_NAME, S_ADDRESS, S_GRADE_NO, P_NO) VALUES (10103, '최학생', '인천', 1, 3);

-- 4. ENROLL 테이블 데이터 입력
INSERT INTO ENROLL(E_NO, S_NO, C_NO, E_DATE) VALUES (111, 10101, 11, '20-02-25');
INSERT INTO ENROLL(E_NO, S_NO, C_NO, E_DATE) VALUES (222, 10101, 22, '20-02-26');
INSERT INTO ENROLL(E_NO, S_NO, C_NO, E_DATE) VALUES (333, 10101, 33, '20-02-27');

-- 5. LECTURE 테이블 데이터 입력
INSERT INTO LECTURE(L_NO, P_NO, E_NO, L_NAME, L_LOCATION) VALUES (1111, 1, 111, '자바완전정복', 'A101');
INSERT INTO LECTURE(L_NO, P_NO, E_NO, L_NAME, L_LOCATION) VALUES (2222, 1, 111, '자바완전정복', 'B101');
INSERT INTO LECTURE(L_NO, P_NO, E_NO, L_NAME, L_LOCATION) VALUES (3333, 1, 111, '자바완전정복', 'C101');

-- 6. 변경된 내용을 DB에 반영
COMMIT;  -- INSERT, UPDATE, DELETE 문은 COMMIT이 필요함.

    


      
      
      