USE team;

-- DROP TABLE
DROP TABLE IF EXISTS ATTACH;
DROP TABLE IF EXISTS UPLOAD;

-- CREATE TABLE
CREATE TABLE UPLOAD
(
    UPLOAD_NO INT NOT NULL AUTO_INCREMENT,  -- INT/BIGINT/SMALLINT
    TITLE VARCHAR(100),   
    CONTENT VARCHAR(100), 
    CREATE_DATE DATETIME,      
    MODIFY_DATE DATETIME,
    CONSTRAINT PK_ATTACH PRIMARY KEY(UPLOAD_NO)  -- AUTO_INCREMENT 사용하려면 PK가 필수
);

CREATE TABLE ATTACH
(
    ATTACH_NO INT NOT NULL AUTO_INCREMENT,   
    PATH VARCHAR(300),     
    ORIGIN VARCHAR(300),     
    FILESYSTEM VARCHAR(42), 
    DOWNLOAD_CNT INT,         
    HAS_THUMBNAIL SMALLINT,          
    UPLOAD_NO INT,
    CONSTRAINT PK_ATTACH PRIMARY KEY(ATTACH_NO), CONSTRAINT FK_ATTACH_UPLOAD FOREIGN KEY(UPLOAD_NO) REFERENCES UPLOAD(UPLOAD_NO) ON DELETE CASCADE
);